import { Festival, FestivalStatus } from '../types';

export const INITIAL_FESTIVALS: Festival[] = [
  // --- PAGINA 1 & 7 ---
  { id: "1777833261185", name: "Animator festival", country: "Polonia", type: "Festival🎬", status: FestivalStatus.PROXIMAMENTE, tasks: [] },
  { id: "1777833261396", name: "Premios Quirino", country: "España", type: "Premios🏆", status: FestivalStatus.PROXIMAMENTE, tasks: [] },
  { id: "1777833261618", name: "Festival Annecy 2027", country: "Annecy", type: "Festival🎬", status: FestivalStatus.PROXIMAMENTE, observations: "cerrado", tasks: [] },
  { id: "1777833261830", name: "Festival Monochile 2027", country: "Chile", type: "Festival🎬", status: FestivalStatus.PROXIMAMENTE, observations: "NO LO ENVIE PORQUE NO SABIA Q EXISTIA", tasks: [] },
  { id: "1777833262057", name: "FEMCINE", country: "Chile", type: "Festival🎬", status: FestivalStatus.PROXIMAMENTE, tasks: [] },
  { id: "1777833262258", name: "Lanterna magica", country: "Brasil", type: "Festival🎬", status: FestivalStatus.PROXIMAMENTE, observations: "que raro q no haya mandado a este", tasks: [] },
  { id: "1777833262502", name: "Annie Awards", country: "Francia?", type: "Premios🏆", status: FestivalStatus.PROXIMAMENTE, tasks: [] },
  { id: "1777833262720", name: "Goya Awards", country: "España", type: "Premios🏆", status: FestivalStatus.PROXIMAMENTE, tasks: [] },
  { id: "1777833263245", name: "Sony Future Filmmaker Awards (Animación)", country: "Los Angeles, EEUU", type: "Premios🏆", status: FestivalStatus.EN_REVISION, category: "Animacion", link: "https://www.sonyfuturefilmmakerawards.com", platform: "Propia", price: "Gratis", tasks: [] },
  { id: "1777833263808", name: "Sony Future Filmmaker Awards (Estudiante)", country: "Los Angeles, EEUU", type: "Premios🏆", status: FestivalStatus.EN_REVISION, category: "Estudiante", link: "https://www.sonyfuturefilmmakerawards.com", platform: "Propia", price: "Gratis", observations: "si lo mande 2 veces", tasks: [] },
  { 
    id: "1777833264760", 
    name: "ENERC SE PROYECTA AMBA", 
    country: "Buenos Aires, ARG", 
    type: "Festival🎬", 
    status: FestivalStatus.SELECCIONADO, 
    deadline: "31/03/2026", 
    category: "Estudiante", 
    nomination: "Mejor Dirección de Arte🎨", 
    link: "http://instagram.com/enercseproyecta", 
    platform: "Youtube (NO LISTADO)", 
    price: "Gratis", 
    observations: "Correcion en el envio. Enviado con el corte final final",
    projectionDate: "2026-05-07",
    projectionLocation: "ENERC, amba, argentina",
    projectionLat: -34.615,
    projectionLng: -58.381,
    tasks: [{ id: "t1", title: "Fijarse si aparecemos en FLIXXO", completed: true }] 
  },
  { 
    id: "1777833264959", 
    name: "ENERC SE PROYECTA CUYO", 
    country: "San Juan, ARG", 
    type: "Festival🎬", 
    status: FestivalStatus.SELECCIONADO, 
    newsDate: "20-abr-2026", 
    category: "Estudiante", 
    nomination: "Sin confirmar", 
    link: "https://docs.google.com/forms/d/e/1FAIpQLSedwNXp8hoaPraChs89VycWXrBK2UXrI0FRzq4wLQqxSSZhlw/viewform", 
    platform: "Youtube (NO LISTADO)", 
    price: "Gratis", 
    observations: "Enviado 27-3-26",
    projectionLocation: "ENERC Sede CUYO",
    projectionLat: -31.5375,
    projectionLng: -68.5363,
    tasks: [
      { id: "t2", title: "mandar el master", completed: true },
      { id: "t3", title: "Preguntar por Laureles", completed: true }
    ]
  },
  { id: "1777833265266", name: "LA CINEF - CANNES SHORT FILM", country: "Cannes, FRA", type: "Festival🎬", status: FestivalStatus.NO_SELECCIONADO, category: "Estudiante", link: "https://moncompte.festival-cannes.com/festival/SuiviFestival.aspx/#divSuiviFilm", platform: "Propia", price: "Gratis", observations: "Enviado corte final final con subtitulos en frances embebidos en el mp4", tasks: [] },
  { id: "1777833265465", name: "Festival de Cine Nacional Cine en Grande", country: "Tierra del Fuego, ARG", type: "Festival🎬", status: FestivalStatus.SELECCIONADO, category: "Sección oficial nacional de Cortometrajes", nomination: "Sin confirmar", link: "https://docs.google.com/forms/d/e/1FAIpQLSfeDlh6uTt2mnEJUty_amlB6G4DtDWUp1wXpcLcYpsxVTGj_g/viewform", platform: "Propia", price: "Gratis", observations: "Carpeta en Archivos Distribucion con Poster, Stills y Foto Dir", projectionLocation: "A confirmar", tasks: [] },
  { id: "1777833265689", name: "II Festival Internacional Goitacá de Cine", country: "Campos dos Goytacas, BRA", type: "Festival🎬", status: FestivalStatus.EN_REVISION, category: "Cabrunquinho", link: "https://docs.google.com/forms/d/e/1FAIpQLSfTtlIAtkRDeyqX4-s9ce5RGgmH6V0pRRDHdfJI1XUdXhoVhw/viewform", platform: "Youtube (NO LISTADO)", price: "Gratis", observations: "Revisar", tasks: [] },
  { id: "1777833265920", name: "LOBITO Festival 2026", country: "Tandil, ARG", type: "Festival🎬", status: FestivalStatus.SELECCIONADO, category: "Cortometraje", link: "https://docs.google.com/forms/d/e/1FAIpQLSd5saL82lr4VRy3nqTyaz6vIMlu0yc_1tBgzAwM2e3mjouisw/viewform", platform: "Propia", price: "Gratis", observations: "Quedó en la no competitiva", projectionDate: "2026-05-16", projectionLocation: "Espacio Multicultural", projectionLat: -37.3216, projectionLng: -59.1331, tasks: [{ id: "t4", title: "Confirmar asistencia", completed: false }] },
  { id: "1777833266741", name: "Festival Internacional del Fin del mundo", country: "Ushuaia, ARG", type: "Festival🎬", status: FestivalStatus.PROYECTADO, deadline: "31/03/2026", newsDate: "8-abr-2026", category: "Cortometraje", nomination: "Sin confirmar", link: "https://filmfreeway.com/FestivaldelFindelMundoUshuaia", platform: "FilmFreeway", price: "$5 USD", projectionDate: "2026-04-25", projectionLocation: "Casa de la Cultura \"Enriqueta Gastelumendi\"", projectionLat: -54.8019, projectionLng: -68.303, tasks: [] },
  { id: "1777833266913", name: "Festival Universitario de Animación FUA!", country: "Costa Rica", type: "Festival🎬", status: FestivalStatus.EN_REVISION, newsDate: "15-may-2026", category: "Cortometraje internacional", link: "https://filmfreeway.com/FestivalUniversitariodeAnimacion", platform: "FilmFreeway", price: "Gratis", tasks: [] },
  { id: "1777833267126", name: "Festival de Cortos 4ta temporada", country: "Buenos Aires, ARG", type: "Festival🎬", status: FestivalStatus.EN_REVISION, deadline: "31-jul-2026", category: "Cortometraje", link: "https://filmfreeway.com/FestivaldeCortos", platform: "FilmFreeway", price: "Gratis", observations: "Solo tiene una categoria", tasks: [] },
  { id: "1777833267478", name: "Festival Cortogenia 27", country: "España", type: "Festival🎬", status: FestivalStatus.EN_DUDA, link: "https://filmmakers.festhome.com/es/festival/cortogenia", platform: "FestHome", price: "$5", observations: "averiguar", tasks: [] },
  { id: "1777833267706", name: "Epsilon 2da edicion", country: "N/A", type: "Muestra🎞️", status: FestivalStatus.PROXIMAMENTE, link: "https://www.instagram.com/p/DVgIUkzlQBL/", platform: "Propia", price: "Gratis", tasks: [] },
  { id: "1777833267922", name: "OSCARS STUDENT ACADEMY AWARDS", country: "Los Angeles, EEUU", type: "Premios🏆", status: FestivalStatus.DESCALIFICADO, newsDate: "18-jun-2026", category: "Estudiantil", link: "https://www.oscars.org/saa/apply", platform: "FilmFreeway", price: "Gratis", observations: "Descalificados porque solo era para proyectos de tesis.", tasks: [] },
  { id: "1777833269086", name: "La Mujer y el Cine 38 festival", country: "CABA, ARG", type: "Festival🎬", status: FestivalStatus.EN_REVISION, deadline: "22/05/2026", category: "Concurso de cortometrajes", link: "https://www.instagram.com/p/DVn99W3Doyu/", platform: "Propia", price: "Gratis", observations: "Te piden registro de guion en DNDA wtf", tasks: [] },
  { id: "1777833269266", name: "Festival Carton", country: "Buenos Aires, ARG", type: "Festival🎬", status: FestivalStatus.EN_REVISION, newsDate: "26-oct-2026", category: "Estudiante de cine de animación de Argentina", link: "https://filmfreeway.com/AnimacionCarton", platform: "FilmFreeway", price: "Gratis", tasks: [] },
  { id: "1777833269480", name: "Festival Bitbang", country: "Buenos Aires, ARG", type: "Festival🎬", status: FestivalStatus.EN_REVISION, newsDate: "7-sept-2026", category: "Mejor Corto Latinoamericano de Animación de Escuela", link: "https://filmfreeway.com/BITBANG", platform: "FilmFreeway", price: "Gratis", observations: "Hay que mandar datos despues de la seleccion", tasks: [] },
  { id: "1777833269699", name: "Festival Anima", country: "Cordoba, ARG", type: "Festival🎬", status: FestivalStatus.EN_REVISION, newsDate: "31-ago-2026", link: "https://filmfreeway.com/animafestival", platform: "FilmFreeway", price: "Gratis", tasks: [] },
  { id: "1777833269958", name: "Festival Anima Latina", country: "Buenos Aires, ARG", type: "Festival🎬", status: FestivalStatus.EN_REVISION, newsDate: "30-jun-2026", category: "Cortometraje animado latinoamericano/argentino de Escuelas", link: "https://filmfreeway.com/animalatinafestival", platform: "FilmFreeway", price: "Gratis", tasks: [] },
  { id: "1777833270162", name: "Festival Chocofest 2026", country: "Buenos Aires, Argentina", type: "Festival🎬", status: FestivalStatus.EN_REVISION, deadline: "1/07/2026", category: "Cortometraje Animado", link: "https://docs.google.com/forms/d/e/1FAIpQLScBFfvWTctDyBCmDkjSrJCnVlGUlgRNxYSnfDiVHp7pL3kQCw/viewform", platform: "Google Forms", price: "Gratis", observations: "armar un desglose y teaser de 10s", tasks: [] },
  { id: "1777833270387", name: "A98 Cinematic Contest II", country: "N/A", type: "Premios🏆", status: FestivalStatus.EN_DUDA, category: "Animación", link: "https://www.instagram.com/p/DWkht6ElbI-/", platform: "Propia", price: "$12", observations: "No se que onda", tasks: [] },
  { id: "1777833270644", name: "Fest. Int. Cine Prov. BA", country: "Buenos Aires, ARG", type: "Festival🎬", status: FestivalStatus.EN_REVISION, deadline: "1/06/2026", newsDate: "2-jun-2026", category: "Cortometraje", link: "https://institutocultural.gba.gob.ar/articulo-noticia/noticias-ficpba/inscripcion-ficpba-2026", platform: "Propia", price: "gratis", observations: "Puse el email de Pipi como alternativo", tasks: [] },
  { id: "1777833270857", name: "Fest. Lat. Cine Olavarria 2026", country: "Olavarria, ARG", type: "Festival🎬", status: FestivalStatus.EN_REVISION, newsDate: "30-jun-2026", category: "Unica", link: "https://docs.google.com/forms/d/e/1FAIpQLSdS4HMoorT6uzfpedYCXvR-tpKdIiU3TVJuSW5sZBVVDXFLIA/viewform", platform: "Propia", price: "gratis", observations: "Email de Pipi porque pedian datos del realizador", tasks: [] },
  { id: "1777833271082", name: "LINOLEUM Contemporary Animation", country: "Kiev, Ukrania", type: "Festival🎬", status: FestivalStatus.EN_REVISION, newsDate: "16-ago-2026", category: "Competencia Internacional", platform: "FilmFreeway", price: "Gratis", observations: "El festival decide", tasks: [] },
  { id: "1777833271272", name: "Pasinetti film festival", country: "Venecia, Italia", type: "Festival🎬", status: FestivalStatus.EN_REVISION, deadline: "10/04/2026", newsDate: "8-may-2026", category: "Pasinetti Fiction y Vedere Poesia", link: "https://filmfreeway.com/PasinettiFilmFestival", platform: "FilmFreeway", price: "gratis", observations: "El festival decide", tasks: [] },
  { id: "1777833271453", name: "FICA Brasil", country: "Brasil", type: "Festival🎬", status: FestivalStatus.EN_REVISION, newsDate: "18-may-2026", category: "Washington Novaes Environmental", link: "https://filmfreeway.com/FICA-Brazil", platform: "FilmFreeway", price: "gratis", observations: "Postura ecologia emocional", tasks: [] },
  { id: "1777833271623", name: "DIVERCINE", country: "Montevideo, Uruguay", type: "Festival🎬", status: FestivalStatus.EN_REVISION, newsDate: "15-jun-2026", category: "Niños 10-12 años", link: "https://www.instagram.com/festivaldivercine", platform: "Propia", price: "gratis", observations: "Cine para niños y jóvenes.", tasks: [] },
  { id: "1777833271821", name: "BIFAN", country: "Corea del Sur", type: "Festival🎬", status: FestivalStatus.EN_REVISION, newsDate: "1-jun-2026", category: "ellos deciden", link: "bifan.kr", platform: "Propia", price: "gratis", observations: "Requiere Premiere en Corea.", tasks: [] },
  { id: "1777833272014", name: "Festival Anibia", country: "Colombia", type: "Festival🎬", status: FestivalStatus.EN_DUDA, deadline: "11/05/2026", category: "Surgentes competencia latinoamericana", link: "https://filmfreeway.com/anibia", platform: "FilmFreeway", price: "$8", observations: "Hay que pagar", tasks: [] },
  { id: "1777833272185", name: "Seoul Women", country: "Seoul, Corea del Sur", type: "Festival🎬", status: FestivalStatus.EN_REVISION, newsDate: "9-jul-2026", category: "NO competitivos", link: "https://filmfreeway.com/SIWFF", platform: "Propia", price: "gratis", observations: "Solo mujeres directoras.", tasks: [] },
  { id: "1777833273175", name: "HAYAH Festival Panama", country: "Panama", type: "Festival🎬", status: FestivalStatus.EN_DUDA, category: "First Frame", link: "https://filmfreeway.com/HayahInternationalShortFilmFestival", platform: "FilmFreeway", price: "$5", tasks: [] },
  { id: "1777833273451", name: "Baton Rouge Underground", country: "Louisiana, EEUU", type: "Festival🎬", status: FestivalStatus.EN_REVISION, newsDate: "20-jun-2026", category: "Best Student Short", link: "https://filmfreeway.com/BRUnderground", platform: "FilmFreeway", price: "gratis", observations: "Subido con cupon gratis", tasks: [] },
  { id: "1777833273975", name: "Festival de cine de Chascomus", country: "Chascomus, ARG", type: "Festival🎬", status: FestivalStatus.POR_ENVIAR, deadline: "20/06/2026", newsDate: "21-jul-2026", link: "https://www.instagram.com/p/DW3wm-1lsZx/", platform: "Propia", price: "gratis", tasks: [] },
  { id: "1777833274186", name: "Festival Arbolito", country: "Santa Clara del Mar, ARG", type: "Festival🎬", status: FestivalStatus.EN_REVISION, deadline: "1/05/2026", category: "ESCUELAs de cine", link: "https://docs.google.com/forms/d/e/1FAIpQLSebi5rIw_nZI2GCWOXcV4EbGpZM0y8g6_4-KTKvuF8gMstL4Q/viewform", platform: "Propia", price: "gratis", observations: "Realizado en enerc 3 sedes", projectionLocation: "Santa clara del mar", tasks: [] },
  { id: "1777833274373", name: "Festival Uruguayo de Animación FUA!", country: "Uruguay", type: "Festival🎬", status: FestivalStatus.EN_DUDA, price: "$10", observations: "pagan $15 USD de screening fee", tasks: [] },
  { id: "1777833274564", name: "Insomnia festival", country: "Moscu, Rusia", type: "Festival🎬", status: FestivalStatus.EN_REVISION, deadline: "1-jun-2026", category: "Debutoria", link: "https://filmfreeway.com/insomniafestival", platform: "Propia", price: "gratis", tasks: [] },
  { id: "1777833274796", name: "ENERC SE PROYECTA NOA", country: "Jujuy, ARG", type: "Festival🎬", status: FestivalStatus.EN_REVISION, newsDate: "27-may-2026", link: "https://docs.google.com/forms/d/e/1FAIpQLSf_oX3aN3GKNKloZESUIY_lYf6dPmstEKZlEDuyxkL3jKGqjw/viewform", platform: "Propia", price: "gratis", observations: "Cami aprobanos🥺", tasks: [] },
  { id: "1777833275018", name: "La Sur Real film fest", country: "Berlin, Alemania", type: "Festival🎬", status: FestivalStatus.EN_REVISION, deadline: "1-jun-2026", category: "Animación", link: "https://docs.google.com/forms/d/e/1FAIpQLSe3Ob0cjrq3bj72fu6hPzOWJn9-3k7iy_1wLQVXbSd5lBWmOw/viewform", platform: "Propia", price: "gratis", tasks: [] },
  { id: "1777833275246", name: "Macacu 18° edición Cine Escolar", country: "Brasil", type: "Festival🎬", status: FestivalStatus.PROXIMAMENTE, deadline: "30/04/2026", link: "https://www.instagram.com/p/DXXJIfbD54q/", price: "gratis", observations: "es de cortos escolares", projectionLocation: "Cachoeiras de Macacu, rio de janeiro", tasks: [] },
  { id: "1777833275477", name: "festi cine huelva", country: "España", type: "Festival🎬", status: FestivalStatus.POR_ENVIAR, deadline: "31/07/2026", observations: "hasta 31-jul", link: "https://www.instagram.com/p/DW03-DSl2Kh/", tasks: [] },
  { id: "1777833275828", name: "Festival de Cine de General Pico", country: "Gral. Pico, La Pampa, ARG", type: "Festival🎬", status: FestivalStatus.POR_ENVIAR, deadline: "28/05/2026", price: "Gratis", observations: "Sin noticias en IG raro", projectionLocation: "Asociación Italia, general pico", tasks: [] },
  { id: "1777833276011", name: "ENERC SE PROYECTA NEUQUEN", country: "Neuquén, ARG", type: "Festival🎬", status: FestivalStatus.PROYECTADO, deadline: "1/04/2026", category: "Proyección", nomination: "Ninguna", link: "https://www.instagram.com/p/DXnfciLDNs8/", price: "Gratis", observations: "Nunca avisaron que se proyectaba", projectionDate: "2026-04-27", projectionLocation: "cine teatro español, neuquen", tasks: [] },
  { id: "1777833276183", name: "Mini Film Festival", country: "Malasia", type: "Festival🎬", status: FestivalStatus.POR_ENVIAR, deadline: "1/06/2026", link: "https://filmfreeway.com/MiniFilmFestival", platform: "Film Freeway", price: "Gratis", observations: "22 años de recorrido", projectionLocation: "University Malaysia Sarawak", tasks: [] },
  { id: "1777833276662", name: "FestCurtasBH 28°", country: "Belo Horizonte, Brasil", type: "Festival🎬", status: FestivalStatus.POR_ENVIAR, deadline: "17/05/2026", newsDate: "20-oct-2026", link: "https://docs.google.com/forms/d/e/1FAIpQLSeAyy5uvnPJWc8AOARf2BxLdJoYj6VW0ctXTr82-mRO1q9zdw/viewform", platform: "Google Forms", price: "Gratis", observations: "buscan cine de autor", tasks: [] },
  { id: "1777833276843", name: "19° Baixada Animada", country: "Rio de Janeiro, Brasil", type: "Festival🎬", status: FestivalStatus.POR_ENVIAR, deadline: "16/05/2026", category: "Competencia Internacional", link: "https://filmfreeway.com/BAIXADAANIMADAMostraIberoAmericanadeCinemadeAnimao", platform: "Film Freeway", price: "Gratis", observations: "inserción animación brasileña", tasks: [{ id: "t5", title: "Averiguar categoria", completed: false }] },
  { id: "1777833277039", name: "Florianópolis Audiovisual Mercosur", country: "Brasil", type: "Festival🎬", status: FestivalStatus.POR_ENVIAR, deadline: "16/06/2026", link: "https://www.famdetodos.com.br/acesso", platform: "Pagina Web Oficial", price: "Gratis", observations: "categoría específica para Argentina", tasks: [] },
  { id: "1777833277220", name: "Ottawa Animation Festival 2026", country: "Ottawa, Canada", type: "Festival🎬", status: FestivalStatus.POR_ENVIAR, deadline: "31/05/2026", link: "https://www.animationfestival.ca/", platform: "Pagina Web Oficial", tasks: [] },
  { id: "1777833277452", name: "Animayo 2027", country: "España", type: "Festival🎬", status: FestivalStatus.PROXIMAMENTE, deadline: "1/04/2026", link: "https://www.animayo.com/", observations: "Averiguar", tasks: [] },
  { id: "1777833277785", name: "Cine de las alturas 2027", country: "Jujuy, Argentina", type: "Festival🎬", status: FestivalStatus.PROXIMAMENTE, deadline: "17/11/2025", link: "https://www.instagram.com/cine.delasalturas", tasks: [] },
  { id: "1777833278024", name: "Jakarta Film Week", country: "Indonesia", type: "Festival🎬", status: FestivalStatus.POR_ENVIAR, deadline: "5/06/2026", link: "https://jakartafilmweek.com/jakarta-film-submission", platform: "Pagina Web oficial", price: "Gratis", tasks: [] },
  { id: "1777833278236", name: "FAM - Audiovisual Malharro", country: "Mar del Plata, ARG", type: "Festival🎬", status: FestivalStatus.POR_ENVIAR, deadline: "31/05/2026", link: "https://docs.google.com/forms/d/e/1FAIpQLSf9lYqhJZIcgovMlxjOehoDOtvKuralu-87cSJhE6zinT0KbA/viewform", platform: "Forms Google", price: "Gratis", observations: "La Malharro!!!", tasks: [] },
  { id: "1777833278421", name: "Ventana Sur Animation! 2027", country: "Argentina", type: "Festival🎬", status: FestivalStatus.PROXIMAMENTE, deadline: "1/01/2027", tasks: [] },
  { id: "1777833278636", name: "PLUM! Festival 2026", country: "Tafí del Valle, ARG", type: "Festival🎬", status: FestivalStatus.POR_ENVIAR, deadline: "15/09/2026", category: "Comp. Latam Cortos Animados", link: "https://plumanimationfest.com/#latina", price: "Gratis", observations: "Todavía no esta el link de la inscripción", tasks: [] },
  { id: "1777833278867", name: "Pixelatl 2026", country: "México", type: "Festival🎬", status: FestivalStatus.POR_ENVIAR, deadline: "31/08/2026", category: "Corto animación Internacional", link: "https://filmfreeway.com/Pixelatl", platform: "Filmfreeway", price: "Gratis", observations: "enfocado en animación!", tasks: [] },
  { id: "1777833279100", name: "Hiroshima Animación Season 2027", country: "Japon", type: "Festival🎬", status: FestivalStatus.PROXIMAMENTE, deadline: "3/05/2026", tasks: [] },
  { id: "1777833279332", name: "Animafest Zagreb 2027", country: "Croacia", type: "Festival🎬", status: FestivalStatus.PROXIMAMENTE, deadline: "1/05/2026", link: "https://www.animafest.hr/en/2026/festival/about_us", tasks: [] },
  { id: "1777874896214", name: "Es-cultura IV 2026", country: "CABA, ARG", type: "Festival🎬", status: FestivalStatus.POR_ENVIAR, deadline: "26/06/2026", category: "Única", link: "https://docs.google.com/forms/d/e/1FAIpQLScicOPfyqgjJtnhqDSNf19JmQ7TrET3BKdSSXbBnRoiRud4wg/viewform", platform: "Google Forms", price: "Gratis", observations: "Es de Indie", tasks: [] },
  { id: "1777914976215", name: "Zlin Film Festival 2027", country: "R. Checa", type: "Festival🎬", status: FestivalStatus.POR_ENVIAR, deadline: "1/01/2027", link: "https://www.instagram.com/zlinfilmfestival", observations: "Niños y juventudes", tasks: [] },
  { id: "1777936721438", name: "TEST-FESTI", country: "pais-test", type: "Festival🎬", status: FestivalStatus.POR_ENVIAR, deadline: "31/03/2028", newsDate: "13-may-2026", link: "https://script.google.com/macros/s/AKfycbxkTOeaOoVTnxSCI--h_tsLQYC9TLrC4_S9fJ6pYtg/dev", platform: "Google Apps Scripts", price: "test-precio", observations: "test-obs", projectionDate: "2026-05-31", projectionLocation: "la quiaca", tasks: [] },
  { id: "1777955504687", name: "FINCI 2026", country: "CABA, ARG", type: "Festival🎬", status: FestivalStatus.EN_DUDA, deadline: "20/05/2026", category: "Animación o Femenino", link: "https://www.instagram.com/fincifilmfestival", platform: "Google Forms", price: "$5", observations: "priorizan obras nuevas", projectionDate: "2026-06-06", tasks: [] },
  { id: "1777956202021", name: "Festival Bio Bio Chile 2026", country: "Chile", type: "Festival🎬", status: FestivalStatus.EN_DUDA, deadline: "15/05/2026", price: "$4", observations: "Cobran $4", tasks: [] },
  { id: "1777957389371", name: "New Chitose Airport Animation", country: "Japón", type: "Festival🎬", status: FestivalStatus.POR_ENVIAR, deadline: "10/07/2026", newsDate: "15-sept-2026", category: "Animated Short Films", link: "https://filmfreeway.com/NewChitoseAirportInternationalAnimationFestival", platform: "Film Freeway", price: "Gratis", observations: "En un aeropuerto wtf. Cubren alojamiento", tasks: [] },
  { id: "1777958007604", name: "Tokyo Anime Award Festival 2027", country: "Tokyo, Japon", type: "Festival🎬", status: FestivalStatus.PROXIMAMENTE, deadline: "1/01/2027", link: "https://animefestival.jp/en/", platform: "Web Oficial", observations: "No se", tasks: [] },
  { id: "1777958516865", name: "BIAF 2026", country: "Corea del Sur", type: "Festival🎬", status: FestivalStatus.EN_REVISION, deadline: "30/06/2026", newsDate: "15-ago-2026", category: "Estudiantil", link: "https://filmfreeway.com/BIAF", platform: "Film Freeway", price: "Gratis", observations: "Calificador OSCARS", tasks: [] },
  { id: "1777960328044", name: "KuanDu Animation Festival 2026", country: "Taiwan", type: "Festival🎬", status: FestivalStatus.POR_ENVIAR, deadline: "5/07/2026", newsDate: "1-sept-2026", link: "https://filmfreeway.com/KDIAF", platform: "Filmfreeway", price: "Gratis", observations: "enfocado estudiantil", tasks: [] }
];

export const INITIAL_PLATFORMS = [
  { id: "p1", name: "Google Forms", icon: "FileText" },
  { id: "p2", name: "Web Oficial", icon: "Globe" },
  { id: "p3", name: "FilmFreeway", icon: "Award" },
  { id: "p4", name: "FestHome", icon: "Home" },
  { id: "p5", name: "Shortfilmdepot", icon: "Inbox" }
];

